name: bio
channels:
  - defaults
dependencies:
  - pip:
    - certifi==2021.5.30
    - pip==21.2.2
    - setuptools==58.0.4
    - wheel==0.37.1
    - backcall==0.2.0
    - colorama==0.4.5
    - dataclasses==0.8
    - decorator==5.1.1
    - entrypoints==0.4
    - future==0.18.2
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - joblib==1.1.1
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - nest-asyncio==1.5.6
    - numpy==1.19.5
    - pandas==1.0.3
    - parso==0.7.1
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prompt-toolkit==3.0.32
    - pygments==2.13.0
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyzmq==24.0.1
    - scikit-learn==0.22.2
    - scipy==1.5.4
    - six==1.16.0
    - tornado==6.1
    - traitlets==4.3.3
    - typing-extensions==4.1.1
    - wcwidth==0.2.5